
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int DIFERENCIA = 13;
  public static final int PUNTOYCOMMA = 9;
  public static final int INTERSECCION = 11;
  public static final int IG = 7;
  public static final int LLAVEC = 21;
  public static final int PARC = 19;
  public static final int OPERA = 3;
  public static final int LLAVEA = 20;
  public static final int PARA = 18;
  public static final int ID = 5;
  public static final int VIRGUILLA = 17;
  public static final int DOS_PUNTOS = 14;
  public static final int NUM = 6;
  public static final int MINUSCULA = 23;
  public static final int CARACTER = 16;
  public static final int COMMA = 8;
  public static final int ASIGNACION = 15;
  public static final int EOF = 0;
  public static final int CONJ = 2;
  public static final int UNION = 10;
  public static final int error = 1;
  public static final int COMPLEMENTO = 12;
  public static final int MAYUSCULA = 22;
  public static final int EVALUAR = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "OPERA",
  "EVALUAR",
  "ID",
  "NUM",
  "IG",
  "COMMA",
  "PUNTOYCOMMA",
  "UNION",
  "INTERSECCION",
  "COMPLEMENTO",
  "DIFERENCIA",
  "DOS_PUNTOS",
  "ASIGNACION",
  "CARACTER",
  "VIRGUILLA",
  "PARA",
  "PARC",
  "LLAVEA",
  "LLAVEC",
  "MAYUSCULA",
  "MINUSCULA"
  };
}

